spring:
  datasource:
    url: jdbc:h2:mem:poc;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
 
  # enable H2 web console and set url for web console
  # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
